from rest_framework.routers import DefaultRouter
from projects.api.urls import post_router
from django.urls import path, include

router = DefaultRouter()
router.registry.extend(post_router.registry) # projects

# Sets up a default router for DRF views.
# Includes URLs generated by router in projects/api/urls.py
urlpatterns = [
    path("", include(router.urls))
]